// *** Actions needed for initial loading of Music component ***

export const FETCH_EDITORIAL_DATA_START = 'FETCH_EDITORIAL_DATA_START';

export const FETCH_EDITORIAL_DATA_SUCCESS = 'FETCH_EDITORIAL_DATA_SUCCESS';
export const FETCH_RADIO_DATA_SUCCESS = 'FETCH_RADIO_DATA_SUCCESS';
export const FETCH_CHARTS_DATA_SUCCESS = 'FETCH_CHARTS_DATA_SUCCESS';
export const FETCH_TOP100_DATA_SUCCESS = 'FETCH_TOP100_DATA_SUCCESS';
export const FETCH_GOOD_OLD_TIMES_DATA_SUCCESS = 'FETCH_GOOD_OLD_TIMES_DATA_SUCCESS';

export const FETCH_EDITORIAL_DATA_FAIL = 'FETCH_EDITORIAL_DATA_FAIL';
export const FETCH_RADIO_DATA_FAIL = 'FETCH_RADIO_DATA_FAIL';
export const FETCH_CHARTS_DATA_FAIL = 'FETCH_CHARTS_DATA_FAIL';
export const FETCH_TOP100_DATA_FAIL = 'FETCH_TOP100_DATA_FAIL';
export const FETCH_GOOD_OLD_TIMES_DATA_FAIL = 'FETCH_GOOD_OLD_TIMES_DATA_FAIL';

export const FETCH_TRACKLIST_DATA_START = 'FETCH_TRACKLIST_DATA_START';
export const FETCH_TRACKLIST_DATA_SUCCESS = 'FETCH_TRACKLIST_DATA_SUCCESS';
export const FETCH_TRACKLIST_DATA_FAIL = 'FETCH_TRACKLIST_DATA_FAIL';

export const FETCH_ALBUM_DATA_START = 'FETCH_ALBUM_DATA_START';
export const FETCH_ALBUM_DATA_SUCCESS = 'FETCH_ALBUM_DATA_SUCCESS';
export const FETCH_ALBUM_DATA_FAIL = 'FETCH_ALBUM_DATA_FAIL';

export const FETCH_PLAYLIST_DATA_START = 'FETCH_PLAYLIST_DATA_START';
export const FETCH_PLAYLIST_DATA_SUCCESS = 'FETCH_PLAYLIST_DATA_SUCCESS';
export const FETCH_PLAYLIST_DATA_FAIL = 'FETCH_PLAYLIST_DATA_FAIL';