// *** Actions needed for initial loading of Music component ***

export const FETCH_EDITORIAL_DATA_SUCCESS = 'FETCH_EDITORIAL_DATA_SUCCESS';
export const FETCH_RADIO_DATA_SUCCESS = 'FETCH_RADIO_DATA_SUCCESS';
export const FETCH_CHARTS_DATA_SUCCESS = 'FETCH_CHARTS_DATA_SUCCESS';
export const FETCH_TOP100_DATA_SUCCESS = 'FETCH_TOP100_DATA_SUCCESS';
export const FETCH_GOOD_OLD_TIMES_DATA_SUCCESS = 'FETCH_GOOD_OLD_TIMES_DATA_SUCCESS';

export const FETCH_EDITORIAL_DATA_FAIL = 'FETCH_EDITORIAL_DATA_FAIL';
export const FETCH_RADIO_DATA_FAIL = 'FETCH_RADIO_DATA_FAIL';
export const FETCH_CHARTS_DATA_FAIL = 'FETCH_CHARTS_DATA_FAIL';
export const FETCH_TOP100_DATA_FAIL = 'FETCH_TOP100_DATA_FAIL';
export const FETCH_GOOD_OLD_TIMES_DATA_FAIL = 'FETCH_GOOD_OLD_TIMES_DATA_FAIL';
